# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

## Mod Properties

mod_id=hungercontrol
mod_name=Hunger Control
mod_license=MIT
mod_version=1.0.0
mod_group_id=io.github.xvold.hungercontrol
mod_authors=xvolD
mod_description=A configurable hunger exhaustion multiplier for modpack developers.\nAllows fine-tuning of food drain speed via a simple config file.
