org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.2
minecraft_version_range=[1.20.2,1.21)
loader_version=0.15.11
fabric_version=0.91.6+1.20.2
loader_version_range=[0.14.0,)
mapping_channel=official
mapping_version=1.20.2

mod_id=hungercontrol
mod_name=Hunger Control
mod_license=MIT
mod_version=1.0.0
mod_group_id=io.github.xvold.hungercontrol
mod_authors=xvolD
mod_description=A configurable hunger exhaustion multiplier for modpack developers.\nAllows fine-tuning of food drain speed via a simple config file.
